services:
  - type: web
    name: pump-monitoring
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent --worker-connections 1000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PORT
        value: "8000"
    healthCheckPath: /
    autoDeploy: true
    plan: free
    region: singapore 