-- Create pump_monitoring database
CREATE DATABASE IF NOT EXISTS pump_monitoring;
USE pump_monitoring;

-- Create users table for authentication
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create predictions table to store pump prediction data
CREATE TABLE IF NOT EXISTS predictions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pump_id VARCHAR(20) NOT NULL,
    time DATETIME NOT NULL,
    status VARCHAR(20) NOT NULL,
    normal_prob FLOAT,
    fault_prob FLOAT,
    confidence FLOAT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create default admin user (password: admin)
-- Note: This is just for documentation, the actual password hash will be generated by the application
INSERT INTO users (username, password) VALUES ('admin', '$2b$12$1xxxxxxxxxxxxxxxxxxxxuRgPUBVN8qR.nMXF0Z5hMGK2lqSopu');

-- Add sample data for testing
INSERT INTO predictions (pump_id, time, status, normal_prob, fault_prob, confidence) 
VALUES 
('pump1', NOW() - INTERVAL 1 HOUR, 'NORMAL', 0.95, 0.05, 95.0),
('pump1', NOW() - INTERVAL 50 MINUTE, 'NORMAL', 0.92, 0.08, 92.0),
('pump1', NOW() - INTERVAL 40 MINUTE, 'NORMAL', 0.87, 0.13, 87.0),
('pump1', NOW() - INTERVAL 30 MINUTE, 'SUSPECT', 0.71, 0.29, 71.0),
('pump1', NOW() - INTERVAL 20 MINUTE, 'FAULT', 0.25, 0.75, 75.0),
('pump1', NOW() - INTERVAL 10 MINUTE, 'FAULT', 0.15, 0.85, 85.0),
('pump1', NOW() - INTERVAL 5 MINUTE, 'FAULT', 0.05, 0.95, 95.0);

-- Create indexes for better performance
CREATE INDEX idx_predictions_time ON predictions(time);
CREATE INDEX idx_predictions_status ON predictions(status); 